# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d41vHwYNftr5W_44hyov6zNJ8dbX1qka
"""

def remove_vowels(string):
    vowels = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
    return ''.join(char for char in string if char not in vowels)
input_string = "Hello, World!"
result = remove_vowels(input_string)
print(result)